### Site variables ###
title: Jared Goodwin
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    example!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll


### Build settings ##
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

  
### Exclude from processing. ###
exclude:
   - (Unused)
   - Gemfile
   - Gemfile.lock
   - gulpfile.js
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/



### Custom, added settings ###
permalink: pretty

header_pages:
  - work.html
  - blog.html

#featured_work:
#  - work/work2.html
#  - work/work1.html

collections:
    posts:
        permalink: /blog/:path/
    work:
        output: true
        permalink: /:collection/:path/
    categories:
        output: true
        permalink: /blog/:path/

assets:
   sources:
       -_assets/fonts
